/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as ReceiptRefidRouteImport } from './routes/receipt.$refid'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as SiteTrainersRouteImport } from './routes/_site.trainers'
import { Route as SitePlansRouteImport } from './routes/_site.plans'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as AdminMembersIdRouteImport } from './routes/admin.members.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const ReceiptRefidRoute = ReceiptRefidRouteImport.update({
  id: '/receipt/$refid',
  path: '/receipt/$refid',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteTrainersRoute = SiteTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => SiteRoute,
} as any)
const SitePlansRoute = SitePlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/admin/members/$id',
  path: '/admin/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/plans': typeof SitePlansRoute
  '/trainers': typeof SiteTrainersRoute
  '/admin/login': typeof AdminLoginRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$refid': typeof ReceiptRefidRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/plans': typeof SitePlansRoute
  '/trainers': typeof SiteTrainersRoute
  '/admin/login': typeof AdminLoginRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$refid': typeof ReceiptRefidRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/plans': typeof SitePlansRoute
  '/_site/trainers': typeof SiteTrainersRoute
  '/admin/login': typeof AdminLoginRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$refid': typeof ReceiptRefidRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/plans'
    | '/trainers'
    | '/admin/login'
    | '/invoice/$id'
    | '/receipt/$refid'
    | '/admin/'
    | '/admin/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/plans'
    | '/trainers'
    | '/admin/login'
    | '/invoice/$id'
    | '/receipt/$refid'
    | '/'
    | '/admin'
    | '/admin/members/$id'
  id:
    | '__root__'
    | '/_site'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/gallery'
    | '/_site/plans'
    | '/_site/trainers'
    | '/admin/login'
    | '/invoice/$id'
    | '/receipt/$refid'
    | '/_site/'
    | '/admin/'
    | '/admin/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  ReceiptRefidRoute: typeof ReceiptRefidRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMembersIdRoute: typeof AdminMembersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/receipt/$refid': {
      id: '/receipt/$refid'
      path: '/receipt/$refid'
      fullPath: '/receipt/$refid'
      preLoaderRoute: typeof ReceiptRefidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/trainers': {
      id: '/_site/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof SiteTrainersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/plans': {
      id: '/_site/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof SitePlansRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/admin/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SitePlansRoute: typeof SitePlansRoute
  SiteTrainersRoute: typeof SiteTrainersRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SitePlansRoute: SitePlansRoute,
  SiteTrainersRoute: SiteTrainersRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  AdminLoginRoute: AdminLoginRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  ReceiptRefidRoute: ReceiptRefidRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMembersIdRoute: AdminMembersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
