/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as R404RouteImport } from './routes/404'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as ReceiptRefidRouteImport } from './routes/receipt.$refid'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRenewalsRouteImport } from './routes/dashboard.renewals'
import { Route as DashboardRenewRouteImport } from './routes/dashboard.renew'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGraceRouteImport } from './routes/admin.grace'
import { Route as AdminBiometricRouteImport } from './routes/admin.biometric'
import { Route as SiteTrainersRouteImport } from './routes/_site.trainers'
import { Route as SitePlansRouteImport } from './routes/_site.plans'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as AdminMembersIdRouteImport } from './routes/admin.members.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const ReceiptRefidRoute = ReceiptRefidRouteImport.update({
  id: '/receipt/$refid',
  path: '/receipt/$refid',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRenewalsRoute = DashboardRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRenewRoute = DashboardRenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/admin/sms',
  path: '/admin/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGraceRoute = AdminGraceRouteImport.update({
  id: '/admin/grace',
  path: '/admin/grace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBiometricRoute = AdminBiometricRouteImport.update({
  id: '/admin/biometric',
  path: '/admin/biometric',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteTrainersRoute = SiteTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => SiteRoute,
} as any)
const SitePlansRoute = SitePlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/admin/members/$id',
  path: '/admin/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/': typeof SiteIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/search': typeof SearchRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/plans': typeof SitePlansRoute
  '/trainers': typeof SiteTrainersRoute
  '/admin/biometric': typeof AdminBiometricRoute
  '/admin/grace': typeof AdminGraceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/dashboard/renew': typeof DashboardRenewRoute
  '/dashboard/renewals': typeof DashboardRenewalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$refid': typeof ReceiptRefidRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/search': typeof SearchRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/plans': typeof SitePlansRoute
  '/trainers': typeof SiteTrainersRoute
  '/admin/biometric': typeof AdminBiometricRoute
  '/admin/grace': typeof AdminGraceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/dashboard/renew': typeof DashboardRenewRoute
  '/dashboard/renewals': typeof DashboardRenewalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$refid': typeof ReceiptRefidRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_site': typeof SiteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/search': typeof SearchRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/plans': typeof SitePlansRoute
  '/_site/trainers': typeof SiteTrainersRoute
  '/admin/biometric': typeof AdminBiometricRoute
  '/admin/grace': typeof AdminGraceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/dashboard/renew': typeof DashboardRenewRoute
  '/dashboard/renewals': typeof DashboardRenewalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$refid': typeof ReceiptRefidRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/maintenance'
    | '/payment-failed'
    | '/search'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/plans'
    | '/trainers'
    | '/admin/biometric'
    | '/admin/grace'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sms'
    | '/dashboard/renew'
    | '/dashboard/renewals'
    | '/dashboard/settings'
    | '/invoice/$id'
    | '/receipt/$refid'
    | '/admin/'
    | '/admin/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/maintenance'
    | '/payment-failed'
    | '/search'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/plans'
    | '/trainers'
    | '/admin/biometric'
    | '/admin/grace'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sms'
    | '/dashboard/renew'
    | '/dashboard/renewals'
    | '/dashboard/settings'
    | '/invoice/$id'
    | '/receipt/$refid'
    | '/'
    | '/admin'
    | '/admin/members/$id'
  id:
    | '__root__'
    | '/404'
    | '/_site'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/maintenance'
    | '/payment-failed'
    | '/search'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/gallery'
    | '/_site/plans'
    | '/_site/trainers'
    | '/admin/biometric'
    | '/admin/grace'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sms'
    | '/dashboard/renew'
    | '/dashboard/renewals'
    | '/dashboard/settings'
    | '/invoice/$id'
    | '/receipt/$refid'
    | '/_site/'
    | '/admin/'
    | '/admin/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  SiteRoute: typeof SiteRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  SearchRoute: typeof SearchRoute
  AdminBiometricRoute: typeof AdminBiometricRoute
  AdminGraceRoute: typeof AdminGraceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  ReceiptRefidRoute: typeof ReceiptRefidRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMembersIdRoute: typeof AdminMembersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/receipt/$refid': {
      id: '/receipt/$refid'
      path: '/receipt/$refid'
      fullPath: '/receipt/$refid'
      preLoaderRoute: typeof ReceiptRefidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/renewals': {
      id: '/dashboard/renewals'
      path: '/renewals'
      fullPath: '/dashboard/renewals'
      preLoaderRoute: typeof DashboardRenewalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/renew': {
      id: '/dashboard/renew'
      path: '/renew'
      fullPath: '/dashboard/renew'
      preLoaderRoute: typeof DashboardRenewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/admin/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/grace': {
      id: '/admin/grace'
      path: '/admin/grace'
      fullPath: '/admin/grace'
      preLoaderRoute: typeof AdminGraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/biometric': {
      id: '/admin/biometric'
      path: '/admin/biometric'
      fullPath: '/admin/biometric'
      preLoaderRoute: typeof AdminBiometricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/trainers': {
      id: '/_site/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof SiteTrainersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/plans': {
      id: '/_site/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof SitePlansRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/admin/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SitePlansRoute: typeof SitePlansRoute
  SiteTrainersRoute: typeof SiteTrainersRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SitePlansRoute: SitePlansRoute,
  SiteTrainersRoute: SiteTrainersRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface DashboardRouteChildren {
  DashboardRenewRoute: typeof DashboardRenewRoute
  DashboardRenewalsRoute: typeof DashboardRenewalsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRenewRoute: DashboardRenewRoute,
  DashboardRenewalsRoute: DashboardRenewalsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  SiteRoute: SiteRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  SearchRoute: SearchRoute,
  AdminBiometricRoute: AdminBiometricRoute,
  AdminGraceRoute: AdminGraceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmsRoute: AdminSmsRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  ReceiptRefidRoute: ReceiptRefidRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMembersIdRoute: AdminMembersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
